"""add phone number

Revision ID: 8fa59eee8fee
Revises: 14ca23cf39c1
Create Date: 2023-06-01 07:59:30.075676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa59eee8fee'
down_revision = '14ca23cf39c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
