"""add phone number

Revision ID: c6fc5388c49d
Revises: a8e4ffd58348
Create Date: 2023-06-01 07:56:49.581288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6fc5388c49d'
down_revision = 'a8e4ffd58348'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
